apiVersion: v1
kind: Service
metadata:
  name: node-single-page-service
spec:
  selector:
    project: node-single-page
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080 # container listing port
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-single-page-deployment
spec: # configuration of the deployment
  replicas: 1 # default 1 if not specified
  selector:
    matchLabels: # (AND condition)
      project: node-single-page
      author: marco
  template:
    metadata:
      labels:
        project: node-single-page
        author: marco
    spec: # configuration of individual pod
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: node-single-page
          image: 287836408715.dkr.ecr.eu-west-1.amazonaws.com/node-single-page
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 3
            initialDelaySeconds: 10
          securityContext:
            allowPrivilegeEscalation: false